### ISSUE TITLE
Tooling

### ISSUE THREAD

**Issue by otherchris** [otherchris/loudsa#2]
As a developer I should be able to
- [x] one-touch lint -> test -> push -> deploy pipeline
- [x] run unit tests in watch mode
- [x] run api tests 
- [x] lint elixir code in the terminal
- [ ] ELK stack
- [ ] monitoring
